### ISSUE TITLE
有考虑使用"Actions secrets"代替所有env选项吗？

### ISSUE THREAD

**Issue by Eden7Ba23** [Misaka13514/blog#2]
最近在[搞Microsoft 365 E5自动续期](https://github.com/EdenJohnson2006/AutoApiP)的时候发现了一个新功能"Action Secrets"，看起来你已经在部分地方使用了这个功能：
```yaml
env:
  HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
```
但还是有一些地方使用了普通的env选项：
```yaml
env:
  GIT_USER: Misaka13514
  GIT_EMAIL: Misaka13514@gmail.com
  DEPLOY_REPO: Misaka13514/blog
  DEPLOY_BRANCH: master
```
虽然我知道这些东西上secrets有丶小题大做，但我依然认为加进去可能是个比较好的选择．
想知道博主的看法．
